//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Logic.WebServiceAuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceAuthService.AuthWebServiceSoap")]
    public interface AuthWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewUserContract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceRequestModel))]
        SSO.Web.Logic.WebServiceAuthService.RegistrationResposeModel RegisterNewUserContract(SSO.Web.Logic.WebServiceAuthService.RegistrationRequestModel composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewUserContract", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.Web.Logic.WebServiceAuthService.RegistrationResposeModel> RegisterNewUserContractAsync(SSO.Web.Logic.WebServiceAuthService.RegistrationRequestModel composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginContract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceRequestModel))]
        SSO.Web.Logic.WebServiceAuthService.LoginResposeModel LoginContract(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginContract", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.Web.Logic.WebServiceAuthService.LoginResposeModel> LoginContractAsync(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutContract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceRequestModel))]
        SSO.Web.Logic.WebServiceAuthService.LoginResposeModel LogoutContract(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutContract", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.Web.Logic.WebServiceAuthService.LoginResposeModel> LogoutContractAsync(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrationRequestModel : ServiceRequestModel {
        
        private string usernameField;
        
        private string passwordField;
        
        private string fullNameField;
        
        private int userLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
                this.RaisePropertyChanged("UserLevel");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginRequsetModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationRequestModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ServiceRequestModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DateTimeOffset requestDateTimeField;
        
        private string requestIpAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DateTimeOffset RequestDateTime {
            get {
                return this.requestDateTimeField;
            }
            set {
                this.requestDateTimeField = value;
                this.RaisePropertyChanged("RequestDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestIpAddress {
            get {
                return this.requestIpAddressField;
            }
            set {
                this.requestIpAddressField = value;
                this.RaisePropertyChanged("RequestIpAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DateTimeOffset : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginResposeModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationResposeModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ServiceResponseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResposeModel : ServiceResponseModel {
        
        private string usernameField;
        
        private bool isAuthorizedField;
        
        private string accessTokenField;
        
        private int userLevelField;
        
        private DateTimeOffset firstActiveTimeField;
        
        private DateTimeOffset lastActiveTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsAuthorized {
            get {
                return this.isAuthorizedField;
            }
            set {
                this.isAuthorizedField = value;
                this.RaisePropertyChanged("IsAuthorized");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("AccessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
                this.RaisePropertyChanged("UserLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DateTimeOffset FirstActiveTime {
            get {
                return this.firstActiveTimeField;
            }
            set {
                this.firstActiveTimeField = value;
                this.RaisePropertyChanged("FirstActiveTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DateTimeOffset LastActiveTime {
            get {
                return this.lastActiveTimeField;
            }
            set {
                this.lastActiveTimeField = value;
                this.RaisePropertyChanged("LastActiveTime");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrationResposeModel : ServiceResponseModel {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequsetModel : ServiceRequestModel {
        
        private string usernameField;
        
        private string passwordField;
        
        private string accessTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("AccessToken");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthWebServiceSoapChannel : SSO.Web.Logic.WebServiceAuthService.AuthWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthWebServiceSoapClient : System.ServiceModel.ClientBase<SSO.Web.Logic.WebServiceAuthService.AuthWebServiceSoap>, SSO.Web.Logic.WebServiceAuthService.AuthWebServiceSoap {
        
        public AuthWebServiceSoapClient() {
        }
        
        public AuthWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SSO.Web.Logic.WebServiceAuthService.RegistrationResposeModel RegisterNewUserContract(SSO.Web.Logic.WebServiceAuthService.RegistrationRequestModel composite) {
            return base.Channel.RegisterNewUserContract(composite);
        }
        
        public System.Threading.Tasks.Task<SSO.Web.Logic.WebServiceAuthService.RegistrationResposeModel> RegisterNewUserContractAsync(SSO.Web.Logic.WebServiceAuthService.RegistrationRequestModel composite) {
            return base.Channel.RegisterNewUserContractAsync(composite);
        }
        
        public SSO.Web.Logic.WebServiceAuthService.LoginResposeModel LoginContract(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite) {
            return base.Channel.LoginContract(composite);
        }
        
        public System.Threading.Tasks.Task<SSO.Web.Logic.WebServiceAuthService.LoginResposeModel> LoginContractAsync(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite) {
            return base.Channel.LoginContractAsync(composite);
        }
        
        public SSO.Web.Logic.WebServiceAuthService.LoginResposeModel LogoutContract(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite) {
            return base.Channel.LogoutContract(composite);
        }
        
        public System.Threading.Tasks.Task<SSO.Web.Logic.WebServiceAuthService.LoginResposeModel> LogoutContractAsync(SSO.Web.Logic.WebServiceAuthService.LoginRequsetModel composite) {
            return base.Channel.LogoutContractAsync(composite);
        }
    }
}
