//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Logic.WcfAuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfAuthService.IAuthWcfService")]
    public interface IAuthWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWcfService/RegisterNewUserContract", ReplyAction="http://tempuri.org/IAuthWcfService/RegisterNewUserContractResponse")]
        SSO.DataModel.RegistrationResposeModel RegisterNewUserContract(SSO.DataModel.RegistrationRequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWcfService/RegisterNewUserContract", ReplyAction="http://tempuri.org/IAuthWcfService/RegisterNewUserContractResponse")]
        System.Threading.Tasks.Task<SSO.DataModel.RegistrationResposeModel> RegisterNewUserContractAsync(SSO.DataModel.RegistrationRequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWcfService/LoginContract", ReplyAction="http://tempuri.org/IAuthWcfService/LoginContractResponse")]
        SSO.DataModel.LoginResposeModel LoginContract(SSO.DataModel.LoginRequsetModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWcfService/LoginContract", ReplyAction="http://tempuri.org/IAuthWcfService/LoginContractResponse")]
        System.Threading.Tasks.Task<SSO.DataModel.LoginResposeModel> LoginContractAsync(SSO.DataModel.LoginRequsetModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWcfService/LogoutContract", ReplyAction="http://tempuri.org/IAuthWcfService/LogoutContractResponse")]
        SSO.DataModel.LoginResposeModel LogoutContract(SSO.DataModel.LoginRequsetModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWcfService/LogoutContract", ReplyAction="http://tempuri.org/IAuthWcfService/LogoutContractResponse")]
        System.Threading.Tasks.Task<SSO.DataModel.LoginResposeModel> LogoutContractAsync(SSO.DataModel.LoginRequsetModel request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthWcfServiceChannel : SSO.Web.Logic.WcfAuthService.IAuthWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthWcfServiceClient : System.ServiceModel.ClientBase<SSO.Web.Logic.WcfAuthService.IAuthWcfService>, SSO.Web.Logic.WcfAuthService.IAuthWcfService {
        
        public AuthWcfServiceClient() {
        }
        
        public AuthWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SSO.DataModel.RegistrationResposeModel RegisterNewUserContract(SSO.DataModel.RegistrationRequestModel request) {
            return base.Channel.RegisterNewUserContract(request);
        }
        
        public System.Threading.Tasks.Task<SSO.DataModel.RegistrationResposeModel> RegisterNewUserContractAsync(SSO.DataModel.RegistrationRequestModel request) {
            return base.Channel.RegisterNewUserContractAsync(request);
        }
        
        public SSO.DataModel.LoginResposeModel LoginContract(SSO.DataModel.LoginRequsetModel request) {
            return base.Channel.LoginContract(request);
        }
        
        public System.Threading.Tasks.Task<SSO.DataModel.LoginResposeModel> LoginContractAsync(SSO.DataModel.LoginRequsetModel request) {
            return base.Channel.LoginContractAsync(request);
        }
        
        public SSO.DataModel.LoginResposeModel LogoutContract(SSO.DataModel.LoginRequsetModel request) {
            return base.Channel.LogoutContract(request);
        }
        
        public System.Threading.Tasks.Task<SSO.DataModel.LoginResposeModel> LogoutContractAsync(SSO.DataModel.LoginRequsetModel request) {
            return base.Channel.LogoutContractAsync(request);
        }
    }
}
